spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?userUnicode=true&charsetEncoding=utf-8&serverTimezone=UTC
    username: root
    password: elliot@mysql


server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

